### ISSUE TITLE
CPU Only 2 Core Active

### ISSUE THREAD

**Issue by aldi45ckr** [nxcm/nx_device_xiaomi_hm2014811#1]
cpu stuck on 2 core active and only if i change grovendor to performance 4 cpu active

**Comment by AragaoAnderson** [comment]
This isn't a bug. It's a feature of MAKO Hotplug that only enable 4 cores when Load Threshold pass through 80% to save your battery. If you want 4 cores, install Kernel Adiutor and on Hotplug section, put Load Threshold to 0%.

**Comment by AragaoAnderson** [comment]
@aldi45ckr friend. Can you test this boot and see if opening some task, this load 4 cores with Load Threshold on 80%? 

https://mega.nz/#!LJcXXQQZ!oI9XeGoG7Ir-Fzt6kgafDrrf90wSo9nKqrTixskWgCs

**Comment by aldi45ckr** [comment]
If I flash boot.img my phone stuck on miui logo
